name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  # =========================
  # 1. TEST
  # =========================
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Run lint
        run: flake8 .

  # =========================
  # 2. BUILD + SCAN + PUSH
  # =========================
  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/github-action-app:${{ github.sha }} .

      - name: List Docker images
        run: docker images

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/github-action-app:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: '1'

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/github-action-app:${{ github.sha }}

  # =========================
  # 3. DEPLOY
  # =========================
  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Deploy to Docker server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}

          script: |
            echo "Pulling new Docker image..."

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/github-action-app:${{ github.sha }}

            echo "Stopping old container..."

            docker stop github-action-app || true
            docker rm github-action-app || true

            echo "Starting new container..."

            docker run -d \
              --name github-action-app \
              -p 5000:5000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/github-action-app:${{ github.sha }}

            echo "Waiting for application..."

            sleep 5

            echo "Running health check..."

            curl -f http://localhost:5000

            echo "Deployment successful!"
